---

- name: Install repository (RedHat)
  when: ansible_os_family == 'RedHat'
  yumrepo:
    name: influxdb
    description: Influxdb repository
    baseurl: "https://repos.influxdata.com/rhel/$releasever/$basearch/stable"
    enabled: yes
    gpgcheck: yes
    gpgkey: "https://repos.influxdata.com/influxdb.key"


- name: Install repository (Debian)
  when: ansible_os_family == 'Debian'
  apt_repository:
    repo: "deb https://repos.influxdata.com/{{ansible_distribution|lower}} {{ansible_distribution_release|lower}} stable"
    state: present

- name: Install repository key (Debian)
  when: ansible_os_family == 'Debian'
  apt_key:
    url: "https://repos.influxdata.com/influxdb.key"
    state: present


- name: Configure
  template:
    src: influxdb.conf.j2
    dest: "{{ _influxdb_conf }}"
    backup: yes
